[package]
name = "task2"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "=0.1.1", features = ["full"] }
alloy-primitives = "=0.7.7" 
tokio = { version = "1", features = ["full"] }